export const NEWS_SOURCE_REQUEST_SUCCESS = 'NEWS_SOURCE_REQUEST_SUCCESS';
export const NEWS_SOURCE_REQUEST_ERROR = 'NEWS_SOURCE_REQUEST_ERROR';
export const NEWS_SOURCE_REQUEST_START = 'NEWS_SOURCE_REQUEST_START';

export const TOP_NEWS_REQUEST_SUCCESS = 'TOP_NEWS_REQUEST_SUCCESS';
export const TOP_NEWS_REQUEST_ERROR = 'TOP_NEWS_REQUEST_ERROR';
export const TOP_NEWS_REQUEST_START = 'TOP_NEWS_REQUEST_START';

export const NEWS_REQUEST_SUCCESS = 'NEWS_REQUEST_SUCCESS';
export const NEWS_REQUEST_ERROR = 'NEWS_REQUEST_ERROR';
export const NEWS_REQUEST_START = 'NEWS_REQUEST_START';

export const TOTAL_NEWS_RESULTS = 'TOTAL_NEWS_RESULTS';

export const NEWS_DETAILS = 'NEWS_DETAILS';
